local ADDON_NAME, ADDON = ...

ADDON.DB.Restrictions = {
[5784] = function() return (ADDON.playerIsClass("WARLOCK")) end, -- Felsteed
[13819] = function() return (ADDON.playerIsClass("PALADIN")) end, -- Warhorse
[23161] = function() return (ADDON.playerIsClass("WARLOCK")) end, -- Dreadsteed
[23214] = function() return (ADDON.playerIsClass("PALADIN")) end, -- Charger
[34767] = function() return (ADDON.playerIsClass("PALADIN")) and (ADDON.playerIsRace("BloodElf")) end, -- Thalassian Charger
[34769] = function() return (ADDON.playerIsClass("PALADIN")) and (ADDON.playerIsRace("BloodElf")) end, -- Thalassian Warhorse
[44151] = function() return (ADDON.playerHasProfession(202)) end, -- Turbo-Charged Flying Machine
[44153] = function() return (ADDON.playerHasProfession(202)) end, -- Flying Machine
[48778] = function() return (ADDON.playerIsClass("DEATHKNIGHT")) end, -- Acherus Deathcharger
[54729] = function() return (ADDON.playerIsClass("DEATHKNIGHT")) end, -- Winged Steed of the Ebon Blade
[61309] = function() return (ADDON.playerHasProfession(197)) end, -- Magnificent Flying Carpet
[61451] = function() return (ADDON.playerHasProfession(197)) end, -- Flying Carpet
[66906] = function() return (ADDON.playerIsClass("PALADIN")) end, -- Argent Charger
[69820] = function() return (ADDON.playerIsClass("PALADIN")) and (ADDON.playerIsRace("Tauren")) end, -- Sunwalker Kodo
[69826] = function() return (ADDON.playerIsClass("PALADIN")) and (ADDON.playerIsRace("Tauren")) end, -- Great Sunwalker Kodo
[73629] = function() return (ADDON.playerIsClass("PALADIN")) and (ADDON.playerIsRace("Draenei") or ADDON.playerIsRace("LightforgedDraenei")) end, -- Exarch's Elekk
[73630] = function() return (ADDON.playerIsClass("PALADIN")) and (ADDON.playerIsRace("Draenei") or ADDON.playerIsRace("LightforgedDraenei")) end, -- Great Exarch's Elekk
[75596] = function() return (ADDON.playerHasProfession(197)) end, -- Frosty Flying Carpet
[169952] = function() return (ADDON.playerHasProfession(197)) end, -- Creeping Carpet
[171844] = function() return (ADDON.playerHasProfession(165)) end, -- Dustmane Direwolf
[200175] = function() return (ADDON.playerIsClass("DEMONHUNTER")) end, -- Felsaber
[229376] = function() return (ADDON.playerIsClass("MAGE")) end, -- Archmage's Prismatic Disc
[229377] = function() return (ADDON.playerIsClass("PRIEST")) end, -- High Priest's Lightsworn Seeker
[229385] = function() return (ADDON.playerIsClass("MONK")) end, -- Ban-Lu, Grandmaster's Companion
[229386] = function() return (ADDON.playerIsClass("HUNTER")) end, -- Huntmaster's Loyal Wolfhawk
[229387] = function() return (ADDON.playerIsClass("DEATHKNIGHT")) end, -- Deathlord's Vilebrood Vanquisher
[229417] = function() return (ADDON.playerIsClass("DEMONHUNTER")) end, -- Slayer's Felbroken Shrieker
[229438] = function() return (ADDON.playerIsClass("HUNTER")) end, -- Huntmaster's Fierce Wolfhawk
[229439] = function() return (ADDON.playerIsClass("HUNTER")) end, -- Huntmaster's Dire Wolfhawk
[231434] = function() return (ADDON.playerIsClass("ROGUE")) end, -- Shadowblade's Murderous Omen
[231435] = function() return (ADDON.playerIsClass("PALADIN")) end, -- Highlord's Golden Charger
[231442] = function() return (ADDON.playerIsClass("SHAMAN")) end, -- Farseer's Raging Tempest
[231523] = function() return (ADDON.playerIsClass("ROGUE")) end, -- Shadowblade's Lethal Omen
[231524] = function() return (ADDON.playerIsClass("ROGUE")) end, -- Shadowblade's Baneful Omen
[231525] = function() return (ADDON.playerIsClass("ROGUE")) end, -- Shadowblade's Crimson Omen
[231587] = function() return (ADDON.playerIsClass("PALADIN")) end, -- Highlord's Vengeful Charger
[231588] = function() return (ADDON.playerIsClass("PALADIN")) end, -- Highlord's Vigilant Charger
[231589] = function() return (ADDON.playerIsClass("PALADIN")) end, -- Highlord's Valorous Charger
[232412] = function() return (ADDON.playerIsClass("WARLOCK")) end, -- Netherlord's Chaotic Wrathsteed
[238452] = function() return (ADDON.playerIsClass("WARLOCK")) end, -- Netherlord's Brimstone Wrathsteed
[238454] = function() return (ADDON.playerIsClass("WARLOCK")) end, -- Netherlord's Accursed Wrathsteed
[270562] = function() return (ADDON.playerIsClass("PALADIN")) and (ADDON.playerIsRace("DarkIronDwarf")) end, -- Darkforge Ram
[270564] = function() return (ADDON.playerIsClass("PALADIN")) and (ADDON.playerIsRace("Dwarf") or ADDON.playerIsRace("DarkIronDwarf")) end, -- Dawnforge Ram
[290608] = function() return (ADDON.playerIsClass("PALADIN")) and (ADDON.playerIsRace("ZandalariTroll")) end, -- Crusader's Direhorn
}