local _, ADDON = ...

ADDON.DB.Tradable = {
[196] = true, -- Spectral Tiger
[197] = true, -- Swift Spectral Tiger
[204] = true, -- Turbo-Charged Flying Machine
[205] = true, -- Flying Machine
[211] = true, -- X-51 Nether-Rocket
[212] = true, -- X-51 Nether-Rocket X-TREME
[230] = true, -- Big Battle Bear
[240] = true, -- Mechano-Hog
[275] = true, -- Mekgineer's Chopper
[285] = true, -- Flying Carpet
[328] = true, -- Magic Rooster
[366] = true, -- Crimson Deathcharger
[372] = true, -- Wooly White Rhino
[407] = true, -- Sandstone Drake
[408] = true, -- Mottled Drake
[412] = true, -- Amani Dragonhawk
[418] = true, -- Savage Raptor
[420] = true, -- Subdued Seahorse
[426] = true, -- Swift Shorestrider
[430] = true, -- Swift Springstrider
[431] = true, -- Swift Lovebird
[432] = true, -- White Riding Camel
[433] = true, -- Corrupted Hippogryph
[447] = true, -- Feldrake
[451] = true, -- Jeweled Onyx Panther
[456] = true, -- Sapphire Panther
[457] = true, -- Jade Panther
[458] = true, -- Ruby Panther
[459] = true, -- Sunstone Panther
[469] = true, -- Depleted-Kyparium Rocket
[470] = true, -- Geosynchronous World Spinner
[522] = true, -- Sky Golem
[532] = true, -- Ghastly Charger
[657] = true, -- Garn Nighthowl
[762] = true, -- Coalfist Gronnling
[769] = true, -- Minion of Grumpus
[797] = true, -- Steelbound Devourer
[928] = true, -- Dune Scavenger
[956] = true, -- Leaping Veinseeker
[999] = true, -- Xiwyllag ATV
[1018] = true, -- Terrified Pack Mule
[1019] = true, -- Goldenmane
[1028] = true, -- Mecha-Mogul Mk2
[1166] = true, -- Great Sea Ray
[1287] = true, -- Explorer's Jungle Hopper
[1288] = true, -- Explorer's Dunetrekker
[1799] = true, -- Eve's Ghastly Rider
[1843] = true, -- Tiger
[1896] = true, -- Sandstone Drake
[1897] = true, -- Mottled Drake
[1901] = true, -- Amani Dragonhawk
[1907] = true, -- Savage Raptor
[1915] = true, -- Swift Shorestrider
[1920] = true, -- Swift Lovebird
[1921] = true, -- White Riding Camel
[1922] = true, -- Corrupted Hippogryph
[1936] = true, -- Feldrake
[2158] = true, -- Crowd Pummeler 2-30
}
