local ADDON_NAME, ADDON = ...

local L = ADDON.L or {}

-- Expansion
L["Classic"] = EXPANSION_NAME0
L["The Burning Crusade"] = EXPANSION_NAME1
L["Wrath of the Lich King"] = EXPANSION_NAME2
L["Cataclysm"] = EXPANSION_NAME3
L["Mists of Pandaria"] = EXPANSION_NAME4
L["Warlords of Draenor"] = EXPANSION_NAME5
L["Legion"] = EXPANSION_NAME6
L["Battle for Azeroth"] = EXPANSION_NAME7

-- Source
L["Drop"] = BATTLE_PET_SOURCE_1
L["Quest"] = BATTLE_PET_SOURCE_2
L["Vendor"] = BATTLE_PET_SOURCE_3
L["Profession"] = BATTLE_PET_SOURCE_4
L["Achievement"] = BATTLE_PET_SOURCE_6
L["World Event"] = BATTLE_PET_SOURCE_7
L["Promotion"] = BATTLE_PET_SOURCE_8
L["Shop"] = BATTLE_PET_SOURCE_10
L["Instance"] = INSTANCE
L["Reputation"] = REPUTATION
L["Garrison"] = GARRISON_LOCATION_TOOLTIP
L["PVP"] = PVP
L["Repair"] = MINIMAP_TRACKING_REPAIR
L["Expansion"] = EXPANSION_FILTER_TEXT
L["Island Expedition"] = ISLANDS_HEADER
L["Class"] = CLASS

L["Basilisks"] = "Basilisks"
L["Bats"] = "Bats"
L["Bears"] = "Bears"
L["Black Market"] = "Black Market"
L["Boars"] = "Boars"
L["Brontosaurus"] = "Brontosaurus"
L["Camels"] = "Camels"
L["Cats"] = "Cats"
L["Chimeras"] = "Chimeras"
L["Clefthooves"] = "Clefthooves"
L["Coursers"] = "Coursers"
L["Cranes"] = "Cranes"
L["Crawgs"] = "Crawgs"
L["Demonic Hounds"] = "Demonic Hounds"
L["Devices"] = "Devices"
L["Direhorns"] = "Direhorns"
L["Dragonhawks"] = "Dragonhawks"
L["Drakes"] = "Drakes"
L["Elekks"] = "Elekks"
L["Elementals"] = "Elementals"
L['FAVOR_DISPLAYED'] = "All Displayed"
L['FAVOR_PER_CHARACTER'] = "Per Character"
L["Family"] = "Family"
L["Fishes"] = "Fishes"
L["Flying"] = "Flying"
L["Foxes"] = "Foxes"
L["Goats"] = "Goats"
L["Gronnlings"] = "Gronnlings"
L["Ground"] = "Ground"
L["Gryphons"] = "Gryphons"
L["Hawks"] = "Hawks"
L["Hawkstriders"] = "Hawkstriders"
L["Hidden"] = "Hidden"
L["Hippogryphs"] = "Hippogryphs"
L["Horses"] = "Horses"
L["Hounds"] = "Hounds"
L["Hyena"] = "Hyena"
L["Infernals"] = "Infernals"
L["Jellyfishes"] = "Jellyfishes"
L["Kirin"] = "Kirin"
L["Kodos"] = "Kodos"
L["Mammoths"] = "Mammoths"
L["Mechanical"] = "Mechanical"
L["Mechanostriders"] = "Mechanostriders"
L["Moose"] = "Moose"
L["Mushan"] = "Mushan"
L["Only usable"] = "Only usable"
L["Parasites"] = "Parasites"
L["Parrots"] = "Parrots"
L["Passenger"] = "Passenger"
L["Phoenixes"] = "Phoenixes"
L["Pterodactyl"] = "Pterodactyl"
L["Rams"] = "Rams"
L["Raptors"] = "Raptors"
L["Rats"] = "Rats"
L["Ravagers"] = "Ravagers"
L["Ravens"] = "Ravens"
L["Rays"] = "Rays"
L["Reset filters"] = "Reset filters"
L["Rhinos"] = "Rhinos"
L["Riverbeasts"] = "Riverbeasts"
L["Scorpions"] = "Scorpions"
L["Sea Dwellers"] = "Sea Dwellers"
L["Seahorses"] = "Seahorses"
L["Serpents"] = "Serpents"
L["Show in Collections"] = "Show in Collections"
L["Silithids"] = "Silithids"
L["Spiders"] = "Spiders"
L["Talbuks"] = "Talbuks"
L["Tallstriders"] = "Tallstriders"
L["TASK_END"] = "[MJE] Phew! I'm done."
L["TASK_FAVOR_START"] = "[MJE] Reapplying stars all over your mounts. Please wait a few seconds until I'm finished."
L["Transform"] = "Transform"
L["Trilobites"] = "Trilobites"
L["Turtles"] = "Turtles"
L["Underwater"] = "Underwater"
L["Water Striders"] = "Water Striders"
L["Water Walking"] = "Water Walking"
L["Wolves"] = "Wolves"
L["Wyverns"] = "Wyverns"
L["Yaks"] = "Yaks"
L["Yeti"] = "Yetis"

ADDON.L = L