local ADDON_NAME = ...;

L = CoreFramework:GetModule("Localization", "1.1"):NewLocalization(ADDON_NAME, "ruRU");

L["Achievement"] = "Достижение" -- Needs review
L["Bats"] = "Летучие мыши" -- Needs review
L["Bears"] = "Медведи" -- Needs review
L["Birds"] = "Птицы" -- Needs review
L["Black Market"] = "Черный рынок" -- Needs review
L["Boars"] = "Кабаны" -- Needs review
L["Camels"] = "Верблюды" -- Needs review
L["Cats"] = "Кошки" -- Needs review
L["Chimeras"] = "Химеры" -- Needs review
L["Class"] = "Класс" -- Needs review
L["Clefthooves"] = "Копытни" -- Needs review
L["Cloud Serpents"] = "Облачные змеи" -- Needs review
L["Coursers"] = "скакун";
L["Cranes"] = "Журавли" -- Needs review
L["Devices"] = "Устройства" -- Needs review
L["Direhorns"] = "Дикороги" -- Needs review
L["Dragonhawks"] = "Дракондоры" -- Needs review
L["Drakes"] = "Драконы" -- Needs review
L["Drop"] = "Добыча" -- Needs review
L["Elekks"] = "Элекки" -- Needs review
L["Family"] = "Семейство" -- Needs review
L["Fishes"] = "Рыбы";
L["Foxes"] = "лисицы";
L["Flying"] = "Летающий" -- Needs review
L["Garrison"] = "Гарнизон" -- Needs review
L["Goats"] = "Козлы" -- Needs review
L["Gronnlings"] = "Малые гронны" -- Needs review
L["Ground"] = "Наземный" -- Needs review
L["Gryphons"] = "Грифоны" -- Needs review
L["Hawks"] = "Ястребы" -- Needs review
L["Hawkstriders"] = "Крылобеги" -- Needs review
L["Hidden"] = "Скрытые" -- Needs review
L["Hide"] = "Скрыть" -- Needs review
L["Hippogryphs"] = "Гиппогрифы" -- Needs review
L["Horses"] = "Лошади" -- Needs review
L["Hounds"] = "Гончие" -- Needs review
L["Infernals"] = "инферналов";
L["Jellyfishes"] = "Медузы";
L["Instance"] = "Подземелье" -- Needs review
L["Kirin"] = "Ветророги" -- Needs review
L["Kodos"] = "Кодо" -- Needs review
L["Mammoths"] = "Мамонты" -- Needs review
L["Mechanical"] = "Механизмы" -- Needs review
L["Mechanostriders"] = "Механодолгоноги" -- Needs review
L["Moose"] = "Лось"
L["Mushan"] = "Мушаны" -- Needs review
L["Only usable"] = "Только доступные" -- Needs review
L["Passenger"] = "Пассажирский" -- Needs review
L["Phoenixes"] = "Фениксы" -- Needs review
L["Profession"] = "Профессия" -- Needs review
L["Promotion"] = "Промо-акция" -- Needs review
L["Pterodactyl"] = "Птеродактили" -- Needs review
L["PVP"] = "PVP" -- Needs review
L["Quest"] = "Задание" -- Needs review
L["Rams"] = "Бараны" -- Needs review
L["Raptors"] = "Ящеры" -- Needs review
L["Rats"] = "Крысы";
L["Ravagers"] = "Разорители" -- Needs review
L["Ravens"] = "Вороны" -- Needs review
L["Repair"] = "Ремонт" -- Needs review
L["Reputation"] = "Репутация" -- Needs review
L["Reset filters"] = "Сбросить фильтры"
L["Rhinos"] = "Носороги" -- Needs review
L["Riverbeasts"] = "Речные чудовища" -- Needs review
L["Scorpions"] = "Скорпионы" -- Needs review
L["Seahorses"] = "Морские коньки" -- Needs review
L["Show"] = "Показать" -- Needs review
L["Silithids"] = "Силитиды" -- Needs review
L["Spiders"] = "пауки";
L["Talbuks"] = "Талбуки" -- Needs review
L["Tallstriders"] = "Долгоноги" -- Needs review
L["Talonbirds"] = "Вороны" -- Needs review
L["Transform"] = "Универсальный" -- Needs review
L["Turtles"] = "Черепахи" -- Needs review
L["Underwater"] = "Подводные" -- Needs review
L["Vendor"] = "Торговец" -- Needs review
L["Water Striders"] = "Водные долгоноги" -- Needs review
L["Water Walking"] = "Хождение по воде" -- Needs review
L["Wolves"] = "Волки" -- Needs review
L["World Event"] = "Игровые события" -- Needs review
L["Wyverns"] = "Виверны" -- Needs review
L["Yaks"] = "Яки" -- Needs review
L["Yeti"] = "Йети" -- Needs review

--L["Expansion"] = "Erweiterung";
